// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyyfmgspbfmhgjeoefbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5eWZtZ3NwYmZtaGdqZW9lZmJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1ODM1MTAsImV4cCI6MjA2NjE1OTUxMH0.yO2S9t8B0l58hEsjYvVvlB67FUzAe3GRqemrEWEzctc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);